# Generated by Django 2.2 on 2020-08-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('students_reported', models.IntegerField()),
                ('students_recovered', models.IntegerField()),
                ('students_active', models.IntegerField()),
                ('faculty_reported', models.IntegerField()),
                ('faculty_recovered', models.IntegerField()),
                ('faculty_active', models.IntegerField()),
                ('total_reported', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('total_active', models.IntegerField()),
                ('report_date', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
    ]
